dataset:
    dataset_path: ./fake_data

training:
    batch_size: 64
    eval_batch_size: 64
    epochs: 5
    log_per_epoch: 1
    eval_interval: 1
    checkpoint_interval: 1

model:
    name: HRM_debug

wandb:
    on_use: False