training:
    batch_size: 512
    eval_batch_size: 512
    epochs: 100000
    log_per_epoch: 100
    eval_interval: 5000
    checkpoint_interval: 5000

    optimizer: adam_atan2

model:
    name: HRM_default